//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandBox.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestorInfo", Namespace="http://schemas.datacontract.org/2004/07/GridProteinFolding.Services.DistributedSe" +
        "rvice")]
    [System.SerializableAttribute()]
    public partial class RequestorInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string macAddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string machineNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string macAddr {
            get {
                return this.macAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.macAddrField, value) != true)) {
                    this.macAddrField = value;
                    this.RaisePropertyChanged("macAddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string machineName {
            get {
                return this.machineNameField;
            }
            set {
                if ((object.ReferenceEquals(this.machineNameField, value) != true)) {
                    this.machineNameField = value;
                    this.RaisePropertyChanged("machineName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service.ParamWcf", Namespace="http://schemas.datacontract.org/2004/07/GridProteinFolding.WCF.ServiceDistributed" +
        "")]
    [System.SerializableAttribute()]
    public partial class ServiceParamWcf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GridProteinFolding.Middle.Helpers.ConfigurationHelpers.Param paramField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GridProteinFolding.Middle.Helpers.ConfigurationHelpers.Param param {
            get {
                return this.paramField;
            }
            set {
                if ((object.ReferenceEquals(this.paramField, value) != true)) {
                    this.paramField = value;
                    this.RaisePropertyChanged("param");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Echo", ReplyAction="http://tempuri.org/IService/EchoResponse")]
        string Echo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOneProcess", ReplyAction="http://tempuri.org/IService/GetOneProcessResponse")]
        SandBox.ServiceReference.ServiceParamWcf GetOneProcess(SandBox.ServiceReference.RequestorInfo requestorInf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOneProcessGui", ReplyAction="http://tempuri.org/IService/GetOneProcessGuiResponse")]
        SandBox.ServiceReference.ServiceParamWcf GetOneProcessGui(System.Guid guid, SandBox.ServiceReference.RequestorInfo requestorInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetOneProcessGuiForETL", ReplyAction="http://tempuri.org/IService/GetOneProcessGuiForETLResponse")]
        SandBox.ServiceReference.ServiceParamWcf GetOneProcessGuiForETL(System.Guid guid, SandBox.ServiceReference.RequestorInfo requestorInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetOneProcess", ReplyAction="http://tempuri.org/IService/SetOneProcessResponse")]
        byte SetOneProcess(GridProteinFolding.Middle.Helpers.ConfigurationHelpers.Param param, GridProteinFolding.Middle.Helpers.EnumsHelpers.BasicEnums.State state, SandBox.ServiceReference.RequestorInfo requestorInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SetOneProcessByGuid", ReplyAction="http://tempuri.org/IService/SetOneProcessByGuidResponse")]
        byte SetOneProcessByGuid(System.Guid guid, GridProteinFolding.Middle.Helpers.EnumsHelpers.BasicEnums.State state, SandBox.ServiceReference.RequestorInfo requestorInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetStatus", ReplyAction="http://tempuri.org/IService/GetStatusResponse")]
        byte GetStatus(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetGuidsToApplications", ReplyAction="http://tempuri.org/IService/GetGuidsToApplicationsResponse")]
        System.Guid[] GetGuidsToApplications();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : SandBox.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<SandBox.ServiceReference.IService>, SandBox.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Echo() {
            return base.Channel.Echo();
        }
        
        public SandBox.ServiceReference.ServiceParamWcf GetOneProcess(SandBox.ServiceReference.RequestorInfo requestorInf) {
            return base.Channel.GetOneProcess(requestorInf);
        }
        
        public SandBox.ServiceReference.ServiceParamWcf GetOneProcessGui(System.Guid guid, SandBox.ServiceReference.RequestorInfo requestorInfo) {
            return base.Channel.GetOneProcessGui(guid, requestorInfo);
        }
        
        public SandBox.ServiceReference.ServiceParamWcf GetOneProcessGuiForETL(System.Guid guid, SandBox.ServiceReference.RequestorInfo requestorInfo) {
            return base.Channel.GetOneProcessGuiForETL(guid, requestorInfo);
        }
        
        public byte SetOneProcess(GridProteinFolding.Middle.Helpers.ConfigurationHelpers.Param param, GridProteinFolding.Middle.Helpers.EnumsHelpers.BasicEnums.State state, SandBox.ServiceReference.RequestorInfo requestorInfo) {
            return base.Channel.SetOneProcess(param, state, requestorInfo);
        }
        
        public byte SetOneProcessByGuid(System.Guid guid, GridProteinFolding.Middle.Helpers.EnumsHelpers.BasicEnums.State state, SandBox.ServiceReference.RequestorInfo requestorInfo) {
            return base.Channel.SetOneProcessByGuid(guid, state, requestorInfo);
        }
        
        public byte GetStatus(System.Guid guid) {
            return base.Channel.GetStatus(guid);
        }
        
        public System.Guid[] GetGuidsToApplications() {
            return base.Channel.GetGuidsToApplications();
        }
    }
}
