//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridProteinFolding.Entities.Internal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataToProcess
    {
        public Nullable<bool> loadDatFile { get; set; }
        public int totalSitio { get; set; }
        public int isem { get; set; }
        public int maxInterations { get; set; }
        public System.Guid process_guid { get; set; }
        public string file { get; set; }
        public long maxMotionPeerIsem { get; set; }
        public byte modelType { get; set; }
        public double valueOfDelta { get; set; }
        public double beta { get; set; }
        public Nullable<int> targets_id { get; set; }
        public double temperature { get; set; }
        public int recPathEvery { get; set; }
        public int splitFileEvery { get; set; }
    
        public virtual ModelType ModelType1 { get; set; }
        public virtual Process Process { get; set; }
        public virtual Targets Targets { get; set; }
    }
}
