//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridProteinFolding.Entities.Internal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataToResult
    {
        public System.Guid process_guid { get; set; }
        public int valueDivResult { get; set; }
        public int valueDiscard { get; set; }
    
        public virtual Process Process { get; set; }
    }
}
