//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridProteinFolding.Entities.Internal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelType
    {
        public ModelType()
        {
            this.DataToProcess = new HashSet<DataToProcess>();
        }
    
        public byte id { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<DataToProcess> DataToProcess { get; set; }
    }
}
