//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridProteinFolding.Entities.Internal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public Process()
        {
            this.Configuration = new HashSet<Configuration>();
            this.Model = new HashSet<Model>();
            this.Process1 = new HashSet<Process>();
            this.ProcessLog = new HashSet<ProcessLog>();
        }
    
        public System.Guid guid { get; set; }
        public Nullable<System.Guid> guidFather { get; set; }
        public System.DateTime date { get; set; }
        public System.Guid userId { get; set; }
        public byte status_id { get; set; }
        public byte emailNotification { get; set; }
        public string note { get; set; }
        public string label { get; set; }
        public bool crypt { get; set; }
        public string macAddr { get; set; }
        public int configApp_id { get; set; }
        public string machineName { get; set; }
    
        public virtual ConfigApp ConfigApp { get; set; }
        public virtual ICollection<Configuration> Configuration { get; set; }
        public virtual DataToProcess DataToProcess { get; set; }
        public virtual DataToResult DataToResult { get; set; }
        public virtual ICollection<Model> Model { get; set; }
        public virtual Output Output { get; set; }
        public virtual Blob Blob { get; set; }
        public virtual ICollection<Process> Process1 { get; set; }
        public virtual Process Process2 { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<ProcessLog> ProcessLog { get; set; }
    }
}
