//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridProteinFolding.Entities.Internal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessLog
    {
        public long id { get; set; }
        public System.Guid process_guid { get; set; }
        public System.DateTime date { get; set; }
        public byte status_id { get; set; }
        public string who { get; set; }
    
        public virtual Process Process { get; set; }
    }
}
