//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridProteinFolding.Entities.Internal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Targets
    {
        public Targets()
        {
            this.DataToProcess = new HashSet<DataToProcess>();
            this.TargetsCoordinates = new HashSet<TargetsCoordinates>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<DataToProcess> DataToProcess { get; set; }
        public virtual ICollection<TargetsCoordinates> TargetsCoordinates { get; set; }
    }
}
