//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridProteinFolding.UI.ProteinFoldingService.DocumentReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocumentReference.IDocumentManagment")]
    public interface IDocumentManagment {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagment/DocumentEcho", ReplyAction="http://tempuri.org/IDocumentManagment/DocumentEchoResponse")]
        bool DocumentEcho(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagment/UploadDocument", ReplyAction="http://tempuri.org/IDocumentManagment/UploadDocumentResponse")]
        void UploadDocument(string fileName, byte[] data, bool append);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentManagment/ExtractDocument", ReplyAction="http://tempuri.org/IDocumentManagment/ExtractDocumentResponse")]
        void ExtractDocument(string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentManagmentChannel : GridProteinFolding.UI.ProteinFoldingService.DocumentReference.IDocumentManagment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentManagmentClient : System.ServiceModel.ClientBase<GridProteinFolding.UI.ProteinFoldingService.DocumentReference.IDocumentManagment>, GridProteinFolding.UI.ProteinFoldingService.DocumentReference.IDocumentManagment {
        
        public DocumentManagmentClient() {
        }
        
        public DocumentManagmentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentManagmentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentManagmentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentManagmentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool DocumentEcho(string fileName) {
            return base.Channel.DocumentEcho(fileName);
        }
        
        public void UploadDocument(string fileName, byte[] data, bool append) {
            base.Channel.UploadDocument(fileName, data, append);
        }
        
        public void ExtractDocument(string fileName) {
            base.Channel.ExtractDocument(fileName);
        }
    }
}
