//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridProteinFolding.Services.DistributedService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GridProteinFolding.Services.DistributedService.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClassificationOfMotion.
        /// </summary>
        internal static string DirClassificationOfMotion {
            get {
                return ResourceManager.GetString("DirClassificationOfMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coord.
        /// </summary>
        internal static string DirCoord {
            get {
                return ResourceManager.GetString("DirCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeadEnd.
        /// </summary>
        internal static string DirDeadEnd {
            get {
                return ResourceManager.GetString("DirDeadEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram.
        /// </summary>
        internal static string DirHistogram {
            get {
                return ResourceManager.GetString("DirHistogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighbors.
        /// </summary>
        internal static string DirNeighbors {
            get {
                return ResourceManager.GetString("DirNeighbors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        internal static string DirOrigin {
            get {
                return ResourceManager.GetString("DirOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed.
        /// </summary>
        internal static string DirSeed {
            get {
                return ResourceManager.GetString("DirSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isem.
        /// </summary>
        internal static string Isem {
            get {
                return ResourceManager.GetString("Isem", resourceCulture);
            }
        }
    }
}
